Django-1.9.1/django/conf/project_template/project_name/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

django-rest-framework-3.3.3/rest_framework/urls.py
"""
Login and logout views for the browsable API.

Add these to your root URLconf if you're using the browsable API and
your API requires authentication:

    urlpatterns = [
        ...
        url(r'^auth/', include('rest_framework.urls', namespace='rest_framework'))
    ]

In Django versions older than 1.9, the urls must be namespaced as 'rest_framework',
and you should make sure your authentication settings include `SessionAuthentication`.
"""
from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib.auth import views

template_name = {'template_name': 'rest_framework/login.html'}

app_name = 'rest_framework'
urlpatterns = [
    url(r'^login/$', views.login, template_name, name='login'),
    url(r'^logout/$', views.logout, template_name, name='logout'),
]

msap/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^training/', include('training.urls')),
    url(r'^staff/', include('staff.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^report_builder/', include('report_builder.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

training/urls.py
from django.conf.urls import url

from . import views

app_name = 'training'
urlpatterns = [
    # ex: /course/5/
    url(r'^course/(?P<pk>[0-9]+)/$', views.CourseDetailView.as_view(), name='course'),
    url(r'^attendance_all_check/(?P<course_id>[0-9]+)/(?P<clazz_id>[0-9]+)/(?P<attendance_status>[0-9]+)/$', views.AttendanceAllCheck.as_view(), name='attendance_all_check'),
    url(r'^attendance_check/(?P<attendance_id>[0-9]+)/$', views.AttendanceCheck.as_view(), name='attendance_check'),
    url(r'^course_task_solution_hand_set/(?P<solution_id>[0-9]+)/(?P<val>[0-9\.]+)$', views.CourseTaskSolutionHandSet.as_view(), name='course_task_solution_hand_set'),
]

training/models.py
#coding: utf-8

from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
from django.db import transaction

import datetime
from decimal import Decimal
import md5

from reversion import revisions as reversion

from staff.models import SiteUser, Mailing
from contingent.models import Student, Teacher
from tasks.models import BaseTask, BaseSolution

@reversion.register()
class CourseProgramm(models.Model):
    name = models.TextField(blank = False, verbose_name = u'Название')
    creatos = models.ManyToManyField(Teacher, blank = True, verbose_name = u'Составители', related_name = 'course_programms')
    
    def __unicode__(self):
        return u'%s' % self.name

@reversion.register()
class Course(models.Model):
    name     = models.TextField(blank = False, verbose_name = u'Название')
    programm = models.ForeignKey(CourseProgramm, blank = False, verbose_name = u'Программа курса')
    auto_check_code = models.TextField(blank = True, null = True, verbose_name = u'Код для автоматической проверки')
    auto_check_flag = models.BooleanField(default = False, verbose_name = u'Автоматическая проверка')
    students = models.ManyToManyField(Student, related_name = 'courses', verbose_name = u'Студенты')
    teachers = models.ManyToManyField(Teacher, related_name = 'courses_teacher', verbose_name = u'Учителя')
    
    def __unicode__(self):
        return u'%s' % self.name
    
    def get_students(self):
        s = []
        for i in self.students.all():
            i = self.fill_student(i)
            s.append(i)
        return s
    
    def fill_student(self, s):
        s.course_attendances = Attendance.get_or_create_cource(s, self)
        s.course_solutions = CourseTaskSolution.get_or_create_solution_course(s, self)
        s.course_score = CourseScore.get_or_create(s, self)
        return s
    
    def is_auto_check(self):
        return self.auto_check_flag
    
    def add_group(self, g):
        self.students.add(*list(g.students.all()))
    
    def get_absolute_url(self):
        return reverse('training:course', args=[self.pk])
    
    def get_html_url(self):
        return '<a href="%s">%s</a>' % (self.get_absolute_url(), self.name)
    get_html_url.allow_tags = True
    get_html_url.short_description = u'Смотреть на сайте'
    
    def add_students_to_mailing(self, m):
        for s in self.students.all():
            m.to.add(s.user)
    
    def is_student(self, user):
        return self.students.filter(user = user).count() > 0
    
    def is_teacher(self, user):
        return self.teachers.filter(user = user).count() > 0
            
@reversion.register()    
class CourseScore(models.Model):
    course  = models.ForeignKey(Course, verbose_name = u'Курс')
    student = models.ForeignKey(Student, verbose_name = u'Студент')
    
    score_min   = models.DecimalField(max_digits = 5, decimal_places = 2, default = Decimal('0.00'), verbose_name = u'Минимум')
    score_max   = models.DecimalField(max_digits = 5, decimal_places = 2, default = Decimal('0.00'), verbose_name = u'Максимум')
    score_auto  = models.DecimalField(max_digits = 5, decimal_places = 2, default = Decimal('0.00'), verbose_name = u'Авто-оценка')
    score_final = models.DecimalField(max_digits = 5, decimal_places = 2, default = Decimal('0.00'), verbose_name = u'Финальная отметка')
    
    @staticmethod
    def get_or_create(student, course):
        q = CourseScore.objects.filter(course = course).filter(student = student)
        if q.count() > 0:
            return q[0]
        s = CourseScore()
        s.student = student
        s.course = course
        s.save()
        return s
    
    @transaction.atomic()
    @reversion.create_revision()
    def update(self):
        if self.course.is_auto_check():
            code = self.course.auto_check_code
            #TODO: implement
            self.score_max = Decimal("10")
            self.score_min = Decimal("0")
            self.save()
            

class Couple(models.Model):
    name       = models.TextField(blank = False, verbose_name = u'Название')
    short_name = models.TextField(blank = True, verbose_name = u'Сокращенное название')
    time_from  = models.TimeField(blank = False, verbose_name = u'Время начала')
    time_to    = models.TimeField(blank = False, verbose_name = u'Время окончания')
    
    def __unicode__(self):
        return u'%s' % self.name

@reversion.register()
class Class(models.Model):
    CLASS_OK     = 0
    CLASS_BAD    = 1
    CLASS_CANCEL = 2
    CLASS_NO     = 3
    CLASS_STATUS_CHOICES = (
        (CLASS_OK,     u'Состоялось'),
        (CLASS_BAD,    u'Не состоялось'),
        (CLASS_CANCEL, u'Отменено'),
        (CLASS_NO,     u'Не отмечено'),
    )
    
    class Meta:
        ordering = ['date', 'couple__time_from']
    
    course    = models.ForeignKey(Course, blank = False, related_name = 'classes', verbose_name = u'Курс')
    date      = models.DateField(blank = False, verbose_name = u'Дата')
    couple    = models.ForeignKey(Couple, blank = False, verbose_name = u'Пара')
    status    = models.IntegerField(choices = CLASS_STATUS_CHOICES, default = CLASS_NO, verbose_name = u'Статус')
    
    @staticmethod
    def gen_classes(course, date_from, date_to, couple):
        dt = datetime.timedelta(days = 7)
        t0 = date_from
        cnt = 0
        while t0 <= date_to:
            c = Class()
            c.course = course
            c.date = t0
            c.couple = couple
            c.save()
            t0 += dt
            cnt += 1
        return cnt
    
    def is_today(self):
        return datetime.date.today() == self.date

@reversion.register()    
class Attendance(models.Model):
    class Meta:
        ordering = ['clazz__date', 'clazz__couple__time_from']
    
    ATTENDANCE_YES          = 0
    ATTENDANCE_NO           = 1
    ATTENDANCE_NO_BY_REASON = 2
    ATTENDANCE_UNDEFINED    = 3
    
    ATTENDANCE_STATUS_CHOICES = (
        (ATTENDANCE_YES,          u'Присутствовал'),
        (ATTENDANCE_NO,           u'Отсутствовал'),
        (ATTENDANCE_NO_BY_REASON, u'Уважительная причина'),
        (ATTENDANCE_UNDEFINED,    u'Не отмечено'),
    )
    
    clazz   = models.ForeignKey(Class, blank = False, related_name = 'attendances', verbose_name = u'Занятие')
    student = models.ForeignKey(Student, blank = False, related_name = 'attendances', verbose_name = u'Студент')
    status  = models.IntegerField(choices = ATTENDANCE_STATUS_CHOICES, default = ATTENDANCE_UNDEFINED, verbose_name = u'Статус')
    
    @staticmethod
    def get_or_create_class(student, clazz):
        q = Attendance.objects.filter(student = student).filter(clazz = clazz)
        if q.count() > 0:
            return q[0]
        a = Attendance()
        a.clazz = clazz
        a.student = student
        a.save()
        return a
    
    @staticmethod
    def get_or_create_cource(student, course):
        q = Attendance.objects.filter(student = student).filter(clazz__course = course)
        if q.count() != course.classes.count():
            for c in course.classes.all():
                Attendance.get_or_create_class(student, c)
        q = Attendance.objects.filter(student = student).filter(clazz__course = course)
        return q.all()
    
    @staticmethod
    def attendance_all_set_status(course, clazz, status):
        q = Attendance.objects.filter(clazz = clazz).filter(clazz__course = course)
        q.update(status = status)
    
    def rotate(self):
        if self.status == Attendance.ATTENDANCE_YES:
            self.status = Attendance.ATTENDANCE_NO
        else:
            self.status = Attendance.ATTENDANCE_YES
        self.save()

class CourseTask(models.Model):
    class Meta:
        ordering = ['num', ]

    short_name = models.CharField(max_length = 256, null = True, blank = True, verbose_name = u'Короткое название')
    task = models.ForeignKey(BaseTask, verbose_name = u'Описание')
    course = models.ForeignKey(Course, null = True, verbose_name = u'Курс', related_name = 'coursetasks')
    deadline_start = models.DateTimeField(blank = True, null = True, verbose_name = u'Начало сдачи')
    deadline_end = models.DateTimeField(blank = True, null = True, verbose_name = u'Окончание сдачи')
    
    num = models.IntegerField(default = 0, verbose_name = u'Номер задачи в курсе (для сортировки и авто отметки)')
    
    score_min = models.DecimalField(max_digits = 5, decimal_places = 2, default = Decimal('0.00'), verbose_name = u'Минимальная отметка за задачу')
    score_max = models.DecimalField(max_digits = 5, decimal_places = 2, default = Decimal('1.00'), verbose_name = u'Максимальная отметка за задачу')
    
    def __unicode__(self):
        return u'%s' % self.short_name

@reversion.register()
class CourseTaskSolution(models.Model):
    
    SOLUTION_BAD     = 0
    SOLUTION_GOOD    = 1
    SOLUTION_PARTIAL = 2
    
    class Meta:
        ordering = ['task__num', ]
    task = models.ForeignKey(CourseTask, verbose_name = u'Задача')
    student = models.ForeignKey(Student, verbose_name = u'Студент')
    solutions = models.ForeignKey(BaseSolution, null = True, blank = True, verbose_name = u'Решение')
    
    hand_flag = models.BooleanField(default = False, verbose_name = u'Выставить отметку вручную')
    hand_score = models.DecimalField(max_digits = 5, decimal_places = 2, default = Decimal('0.00'), verbose_name = u'Ручная отметка')
    
    def __unicode__(self):
        return u'%s (%s), %s, %s' % (self.task, self.task.task.name, self.task.course, self.student)
    
    def get_score(self):
        if self.hand_flag:
            return self.hand_score
        if self.solutions:
            return 10000
        else:
            return self.task.score_min
    
    def get_status(self):
        if self.get_score() == self.task.score_min:
            return CourseTaskSolution.SOLUTION_BAD
        if self.get_score() == self.task.score_max:

training/forms.py
#coding: utf-8

from django import forms
from django.forms.extras.widgets import SelectDateWidget

from .models import *
from staff.models import *
from contingent.models import *

class CreateClassesForm(forms.Form):
    _selected_action = forms.CharField(widget = forms.MultipleHiddenInput)
    date_start       = forms.DateField(label = u'Дата первого занятия', widget = SelectDateWidget)
    date_end         = forms.DateField(label = u'Дата последнего занятия', widget = SelectDateWidget)
    couples          = forms.ModelChoiceField(queryset = Couple.objects.all(), label=u'Пара')

class AddGroupForm(forms.Form):
    _selected_action = forms.CharField(widget = forms.MultipleHiddenInput)
    group            = forms.ModelChoiceField(queryset = StudentsGroup.objects.all(), label=u'Группа')

training/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.http import HttpResponse
from django.views.generic import View
from django.db import transaction
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import HttpResponseForbidden

from reversion import revisions as reversion

from decimal import Decimal

from .models import *


class CourseDetailView(UserPassesTestMixin, generic.DetailView):
    model = Course
    template_name = 'training/course.html'
    raise_exception = True
    
    def get_context_data(self, **kwargs):
        context = super(CourseDetailView, self).get_context_data(**kwargs)
        u = self.request.user
        context['is_student'] = self.object.is_student(u)
        context['is_teacher'] = self.object.is_teacher(u)
        return context
    
    def test_func(self):
        u = self.request.user
        o = self.get_object()
        return o.is_student(u) or o.is_teacher(u)
    
    
    @method_decorator(login_required())
    def dispatch(self, request, *args, **kwargs):
        return super(CourseDetailView, self).dispatch(request, *args, **kwargs)


class AttendanceAllCheck(View):
    def get(self, request, course_id, clazz_id, attendance_status):
        c1 = get_object_or_404(Course, pk=course_id)
        if not c1.is_teacher(request.user):
            return HttpResponseRedirect(reverse('training:course', args=[course_id]))
        c2 = get_object_or_404(Class,  pk=clazz_id)
        with transaction.atomic(), reversion.create_revision():
            Attendance.attendance_all_set_status(c1, c2, attendance_status)
            reversion.set_user(request.user)
            reversion.set_comment("Setting to %s by %s" % (attendance_status, request.user))
        return HttpResponseRedirect(reverse('training:course', args=[course_id]))

class AttendanceCheck(View):
    def get(self, request, attendance_id):
        a = get_object_or_404(Attendance,  pk=attendance_id)
        if not a.clazz.course.is_teacher(request.user):
            return HttpResponseRedirect(reverse('training:course', args=[a.clazz.course.id]))
        with transaction.atomic(), reversion.create_revision():
            a.rotate()
            reversion.set_user(request.user)
            reversion.set_comment("Rotating by %s" % request.user)
        return HttpResponseRedirect(reverse('training:course', args=[a.clazz.course.id]))

class CourseTaskSolutionHandSet(View):
    def get(self, request, solution_id, val):
        a = get_object_or_404(CourseTaskSolution,  pk=solution_id)
        if not a.task.course.is_teacher(request.user):
            return HttpResponseRedirect(reverse('training:course', args=[a.task.course.id]))
        with transaction.atomic(), reversion.create_revision():
            a.hand_flag = True
            a.hand_score = Decimal(val)
            a.save()
            reversion.set_user(request.user)
            reversion.set_comment("Setting max score to task %s by user %s" % (a, request.user))
        return HttpResponseRedirect(reverse('training:course', args=[a.task.course.id]))

training/templates/training/add_groups_action.html
{% extends "admin/base_site.html" %}
{% load admin_static %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Добавление студентов в курсы:</p>
    <ul>{{ items|unordered_list }}</ul>
    <br />
    <ul>
    {{ form.as_ul }}
    </ul>
    <input type="hidden" name="action" value="add_groups" />
    <input type="submit" name="apply" value="Добавить" />
</form>
{% endblock %}

training/templates/training/course.html
{% extends "admin/base_site.html" %}
{% load admin_static %}

{% block title %}Курс | {{ object.name }}{% endblock %}

{% block extrastyle %}
<style>
    th.today {
        border: 2px solid red;
        border-bottom-width: 0px;
        padding: 1px;
        border-spacing: 0px;
    }
    th.not_today {
        border: no;
        padding: 1px;
        border-spacing: 0px;
    }
    td.today {
        border: 0px solid red;
        border-left-width: 2px;
        border-right-width: 2px;
        border-bottom: 1px solid lightgray;
        padding: 2px;
        border-spacing: 0px;
    }
    td.not_today {
        border-bottom: 1px solid lightgray;
        padding: 2px;
        border-spacing: 0px;
        height: 100%;

    }
    table.clazz tr td {
        border-collapse: collapse;
        border: none;
        font-size: 11px;
        font-weight: 400;
        vertical-align: center;
        text-align: center;
        padding: 1px;
        border-spacing: 0px;
    }
    
    

    table.course tr.hover:hover {
        background-color: #ffa;
        height: 100%;
    }

    
    tr.class_ok {
        background-color: lightgreen;
        border: 1px solid green;
        font-size: 11px;
        text-transform: lowercase;

    }
    tr.class_bad {
        background-color: #FF6666;
        border: 1px solid red;
        font-size: 11px;
        text-transform: lowercase;
    }
    tr.class_cancel {
        background-color: lightyellow;
        border: 1px solid yellow;
        font-size: 11px;
        text-transform: lowercase;
    }
    tr.class_no {
        background-color: lightgray;
        border: 1px solid gray;
        font-size: 11px;
        text-transform: lowercase;
    }
    
    div.attendance_yes {
        background-color: lightgreen;
        border: 1px solid green;
        font-size: 11px;
        height: 100%;
        text-align: center;
    }
    div.attendance_no {
        background-color: #FF6666;
        border: 1px solid red;
        font-size: 11px;
        height: 100%;
        text-align: center;
    }
    div.attendance_undefined {
        background-color: lightgray;
        border: 1px solid gray;
        font-size: 11px;
        text-align: center;
        height: 100%;
    }
    div.attendance_no_by_reason {
        background-color: lightyellow;
        border: 1px solid yellow;
        font-size: 11px;
        height: 100%;
        text-align: center;
    }

    .button_yes {
	background-color:#44c767;
	border:1px solid #18ab29;
	display:inline-block;
	cursor:pointer;
	color:#ffffff;
	font-family:Arial;
	font-size:11px;
	padding:1px 2px;
	text-decoration:none;
    }
    .button_yes:hover {
            background-color:#5cbf2a;
    }
    .button_yes:active {
            position:relative;
            top:1px;
    }


.button_no {
	background-color:#fa0a3a;
	border:1px solid #ab1919;
	display:inline-block;
	cursor:pointer;
	color:#000000;
	font-family:Arial;
	font-size:11px;
	padding:1px 2px;
	text-decoration:none;
}
.button_no:hover {
	background-color:#ff8ab9;
}
.button_no:active {
	position:relative;
	top:1px;
}

a.solution_bad {
    background-color: #ffb3b3;
    padding: 2px 5px;
    text-align: center;	
    text-decoration: none;
    display: inline-block;
}

a.solution_good {
    background-color: #99ff99;
    padding: 2px 5px;
    text-align: center;	
    text-decoration: none;
    display: inline-block;
}

a.solution_partial {
    background-color: #ffff99;
    padding: 2px 5px;
    text-align: center;	
    text-decoration: none;
    display: inline-block;
}



</style>
{% endblock %}

{% block branding %}<h1>{{ object.name }}</h1>{% endblock %}

{% block content %}
<h1>Сегодня {% now "d M Y, l" %}</h1>

{% if is_teacher %}
<p>(Жирным помечен староста).<p>
{% endif %}

<div class="results">
<table id="result_list" class="course">
<thead>
<tr>
<th scope="col"  class="">
   <div class="text"><span>#</span></div>
</th>
<th scope="col"  class="">
   <div class="text"><span>Список студентов</span></div>
</th>
<th scope="col"  class="">
   <div class="text"><span>Группа</span></div>
</th>

{# Почту видит только учитель. #}
{% if is_teacher %}
<th scope="col"  class="">
   <div class="text"><span>E-mail</span></div>
</th>
{% endif %}

{% for i in object.classes.all %}
    {% if i.is_today %}
    <th class="today">
    {% else %}
    <th class="not_today">
    {% endif %}
    <table class="clazz">
    {#<tr><td>{{ i.date|date:"d M" }}</td></tr>#}
    
    {% if i.status == 0 %}
    <tr class="class_ok">
    {% elif i.status == 1 %}
    <tr class="class_bad">
    {% elif i.status == 2 %}
    <tr class="class_cancel">
    {% elif i.status == 3 %}
    <tr class="class_no">
    {% endif %}
    
    <td>{{ i.date|date:"d M" }}</td></tr>
    {% if i.is_today %}
    <tr><td><a href='{% url "training:attendance_all_check" object.id i.id 0%}' class="button_yes">Yes</a></td></tr>
    <tr><td><a href='{% url "training:attendance_all_check" object.id i.id 1%}' class="button_no">No</a></td></tr>
    {% endif %}
    </table>
    
    </th>
{% endfor %}

<th>&nbsp;</th>
{% for i in object.coursetasks.all %}
    <th>{{ i.short_name }}</th>
{% endfor %}
<th>&nbsp;</th>
<th>Итог</th>
{% if object.is_auto_check %}
<th>Авто curr/min/max</th>
{% endif %}

</tr>
</thead>

<tbody>
{% for s in object.get_students %}
<tr class="hover">
<td>{{ forloop.counter }}</td>
<td>{% if s.is_monitor %}<b>{{ s.user.surname }} {{ s.user.name }}</b> {% else %} {{ s.user.surname }} {{ s.user.name }} {% endif %}</td>
<td>{% if s.group %}<a href="{% url 'admin:contingent_studentsgroup_change' s.group.id %}">{{ s.group.name }}</a>{% endif %}</td>
{% if is_teacher %}<td>{{ s.user.email }}</td>{% endif %}
{% for i in s.course_attendances %}
    {% if i.clazz.is_today %}
    <td class="today">
    {% else %}
    <td class="not_today">
    {% endif %}

    {% if i.status == 0 %}
    <div class="attendance_yes">
    {% elif i.status == 1 %}
    <div class="attendance_no">
    {% elif i.status == 2 %}
    <div class="attendance_no_by_reason">
    {% elif i.status == 3 %}
    <div class="attendance_undefined">
    {% endif %}
    {% if is_teacher %}<a href='{% url "training:attendance_check" i.id %}' title="Изменить">X</a>{% endif %}
    </div>
</td>
{% endfor %}
<td>&nbsp;</td>

{% for i in s.course_solutions %}
    <td><a href="{{ i.get_url }}" class="{{ i.get_status_class_css }}" title="Изменить решение">{{ i.get_score }}</a>
    {% if i.is_solution_bad and is_teacher %}<a href="{% url "training:course_task_solution_hand_set" i.id i.task.score_max %}" title="Выставить вручную максимум">+</a>{% endif %}</td>
{% endfor %}
<th>&nbsp;</th>
<td>
{% if is_teacher %}
<a href="{% url 'admin:training_coursescore_change' s.course_score.id %}">{{ s.course_score.score_final }}</a>
{% else %}
{{ s.course_score.score_final }}
{% endif %}
</td>
{% if object.is_auto_check %}
<td>{{ s.course_score.score_auto }}/{{ s.course_score.score_min }}/{{ s.course_score.score_max }}</td>
{% endif %}

</tr>
{% endfor %}
</tbody>
</table>
</div>
{% endblock %}

training/templates/training/create_classes_action.html
{% extends "admin/base_site.html" %}
{% load admin_static %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Создание расписания для курсов</p>
    <ul>{{ items|unordered_list }}</ul>
    <br />
    <ul>
    {{ form.as_ul }}
    </ul>
    <input type="hidden" name="action" value="create_classes" />
    <input type="submit" name="apply" value="Создать" />
</form>
{% endblock %}